name: Update Naukri Profile

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: # This allows you to click the "Run workflow" button manually!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run python naukri.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          MOBILE: ${{ secrets.MOBILE }}
        run: python naukri.py
